quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('login', views.user_login, name='user_login'),
    path('register', views.user_register, name='user_register'),
    path('logout', views.user_logout, name='user_logout'),
    path('new_quiz', views.new_quiz, name='new_quiz'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('edit/<str:quiz_id>', views.edit_quiz, name='edit_quiz'),
    path('add_question/<str:quiz_id>', views.add_question, name='add_question'),
    path('delete_question/<str:quiz_id>', views.delete_question, name='delete_question'),
    path('edit_question_main/<str:quiz_id>', views.edit_question_main, name='edit_question_main'),
    path('edit_question/<str:question_id>', views.edit_question, name='edit_question'),
    path('delete_quiz/<str:quiz_id>', views.delete_quiz, name="delete_quiz"),
    path('user_list_information/<str:quiz_id>', views.user_list_information, name="user_list_information"),
    path('add_user_to_quiz/<str:quiz_id>', views.add_user_to_quiz, name="add_user_to_quiz"),
    path('take_quiz/<str:quiz_id>', views.take_quiz, name="take_quiz"),
    path('begin_quiz/<str:quiz_id>', views.begin_quiz, name='begin_quiz'),
    path('view_submissions/<str:quiz_id>/<str:user_id>', views.view_submissions, name='view_submissions')
]

quiz_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('quiz/', include('quiz.urls')),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Quiz(models.Model):
    users = models.ManyToManyField(UserProfile)
    name = models.CharField(max_length=20)
    quiz_owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='+', null=True, blank=True)
    is_repeatable = models.BooleanField()
    time_limit = models.IntegerField()

    class Meta:
        unique_together = ['name', 'quiz_owner']
    
    def __str__(self):
        return self.name

class Question(models.Model):
    text = models.CharField(max_length=155)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.text

class CorrectAnswer(models.Model):
    text = models.CharField(max_length=155)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        ordering = ['text']

    def __str__(self):
        return self.text

class IncorrectAnswer(models.Model):
    text = models.CharField(max_length=155)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        ordering = ['text']

    def __str__(self):
        return self.text

class Score(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.FloatField()
    expiration_date = models.DateTimeField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.score)

class AnsweredQuestion(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    correct_answers_selected = models.ManyToManyField(CorrectAnswer, blank=True)
    incorrect_answers_selected = models.ManyToManyField(IncorrectAnswer, blank=True)
    score = models.ForeignKey(Score, on_delete=models.CASCADE)
    question_number = models.IntegerField()
    is_correct = models.BooleanField()

    def __str__(self):
        return self.question.text

quiz/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput, max_length=20, min_length=8)
    confirm_password = forms.CharField(widget=forms.PasswordInput, max_length=20, min_length=8)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput, max_length=20)

quiz/views.py
from django.shortcuts import render
from .forms import RegisterForm, LoginForm
from .models import UserProfile, Quiz, Question, CorrectAnswer, IncorrectAnswer, Score, AnsweredQuestion
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta, timezone
from random import shuffle

# Create your views here.
def user_register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User(username=form.cleaned_data['username'])
            if User.objects.filter(username=user.username):
                return render(request, 'quiz/register.html', {'form': form, 'is_logged_in': request.user.is_authenticated, 
                                'isError': True, 'error': 'Username already exists!', 'isActive': 'register'})
            if form.cleaned_data['password'] != form.cleaned_data['confirm_password']:
                return render(request, 'quiz/register.html', {'form': form, 'is_logged_in': request.user.is_authenticated, 
                                'isError': True, 'error': 'Passwords do not match!', 'isActive': 'register'})
            user.set_password(form.cleaned_data['password'])
            user.save()

            profile = UserProfile()
            profile.user = user
            profile.save()
            return HttpResponseRedirect('../')

    form = RegisterForm()
    return render(request, 'quiz/register.html', {'form': form, 'is_logged_in': request.user.is_authenticated, 'isActive': 'register'})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                request.session['is_logged_in'] = True
                return HttpResponseRedirect('/quiz/dashboard')
            else:
                return render(request, 'quiz/login.html', {'form': form, 'is_logged_in': request.user.is_authenticated, 'isActive': 'login',
                                                            'isError': True, 'error': 'Invalid Username/Password, please try again.'})
            return HttpResponseRedirect('../')
    form = LoginForm()
    return render(request, 'quiz/login.html', {'form': form, 'is_logged_in': request.user.is_authenticated, 'isActive': 'login'})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('../')

@login_required
def new_quiz(request):
    if request.method == 'POST':
        name = request.POST['name_input']
        quiz_owner = request.user.userprofile
        time_limit = int(request.POST['time_limit_input'])
        try:
            Quiz.objects.get(quiz_owner=quiz_owner, name=name)
        except Exception:
            pass
        else:
            return render(request, 'quiz/new_quiz.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'new_quiz', 
                                                            'name_value': name, 'isError': True, 'error': 'Quiz name already exists.',
                                                            'time_limit': time_limit})
        if time_limit > 120 or time_limit < 0:
            return render(request, 'quiz/new_quiz.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'new_quiz', 
                                                        'name_value': name, 'isError': True, 'error': 'Time limit must be between 0 and 120 inclusive.',
                                                        'time_limit': time_limit})
        if request.POST['is_repeatable'] == '0':
            is_repeatable = False
        else:
            is_repeatable = True
        quiz = Quiz(name=name, is_repeatable=is_repeatable, quiz_owner=quiz_owner, time_limit=time_limit)
        quiz.save()
        return HttpResponseRedirect('/quiz/dashboard')   
    return render(request, 'quiz/new_quiz.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'new_quiz', 'name_value': '',
                                                    'time_limit': 0})

@login_required
def dashboard(request):
    quiz_owner = request.user.userprofile
    detailed_quiz_member_list = []
    try:
        quiz_owner_list = list(Quiz.objects.filter(quiz_owner=quiz_owner))
    except Exception:
        quiz_owner_list = []
    try:
        quiz_member_list = list(Quiz.objects.filter(users=quiz_owner))
        print(quiz_member_list)
    except Exception:
        quiz_member_list = []
    for quiz in quiz_member_list:
        score_list = []
        score_recent = list(Score.objects.filter(quiz=quiz, user=request.user.userprofile).order_by('-created_date'))
        for score in score_recent:
            score_list.append(score.score)
        score_best = score_list.sort(reverse=True)
        if len(score_recent) == 0:
            score_recent = 'None'
            score_best = 'None'
            if quiz.quiz_owner != None:
                can_take_quiz = True
            else:
                can_take_quiz = False
        else:
            score_recent = score_recent[0].score
            score_best = score_list[0]
            if quiz.quiz_owner != None:
                can_take_quiz = quiz.is_repeatable
            else:
                can_take_quiz = False
        detailed_quiz_member_list.append({'quiz': quiz, 'score_recent': score_recent, 'score_best': score_best, 
                                                'can_take_quiz': can_take_quiz}) 
    return render(request, 'quiz/dashboard.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'dashboard',
                                                    'quiz_owner_list': quiz_owner_list, 'quiz_owner_list_len': len(quiz_owner_list),
                                                    'username': request.user.username, 'detailed_quiz_member_list': detailed_quiz_member_list,
                                                    'quiz_member_list_len': len(quiz_member_list), 'user_id': request.user.userprofile.id})

@login_required
def edit_quiz(request, quiz_id):
    if request.method == 'POST':
        try:
            quiz = Quiz.objects.get(name=quiz_id, quiz_owner=request.user.userprofile)
        except:
            return HttpResponseRedirect('/quiz/dashboard')
        if request.POST['action_dropdown'] == 'nothing':
            return HttpResponseRedirect('/quiz/dashboard')
        if request.POST['action_dropdown'] == 'change_name':
            new_name = request.POST['quiz_name']
            try:
                Quiz.objects.get(name=new_name, quiz_owner=request.user.userprofile)
            except:
                quiz.name = new_name
                quiz.save()
                return HttpResponseRedirect('/quiz/edit/' + quiz.name)
            else:
                quiz.name = new_name
                return render(request, 'quiz/edit_quiz.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'edit_quiz',
                                                'quiz': quiz, 'isError': True, 'error': 'You are already using this quiz name.'})
        if request.POST['action_dropdown'] == 'add_question':
            return HttpResponseRedirect('/quiz/add_question/' + quiz.name)
        
        if request.POST['action_dropdown'] == 'delete_question':
            return HttpResponseRedirect('/quiz/delete_question/' + quiz.name)
        
        if request.POST['action_dropdown'] == 'edit_question':
            return HttpResponseRedirect('/quiz/edit_question_main/' + quiz.name)
        if request.POST['action_dropdown'] == 'delete_quiz':
            return render(request, 'quiz/delete_quiz.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'edit_quiz',
                                                                'quiz': quiz})
        if request.POST['action_dropdown'] == 'change_time_limit':
            time_limit = int(request.POST['time_limit_input'])
            if time_limit < 0 or time_limit > 120:
                return render(request, 'quiz/edit_quiz.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'edit_quiz',
                                                'quiz': quiz, 'isError': True, 'error': 'Time limit must be between 0 and 120 inclusive.'})
        
            else:
                quiz.time_limit = time_limit
                quiz.save()
                return HttpResponseRedirect('/quiz/edit/' + quiz_id)
        if request.POST['action_dropdown'] == 'change_repeatable':
            try:
                request.POST['is_repeatable_input']
            except Exception:
                quiz.is_repeatable = False
                quiz.save()
            else:
                quiz.is_repeatable = True
                quiz.save()
        return HttpResponseRedirect('/quiz/edit/' + quiz_id)
    
    quiz_owner = request.user.userprofile
    try:
        quiz = Quiz.objects.get(name=quiz_id, quiz_owner=quiz_owner)
    except Exception:
        return HttpResponseRedirect('/quiz/dashboard')
    return render(request, 'quiz/edit_quiz.html', {'is_logged_in': request.user.is_authenticated, 'isActive': 'edit_quiz',
                                                    'quiz': quiz})

@login_required
def add_question(request, quiz_id):
    quiz_owner = request.user.userprofile
    try:
        quiz = Quiz.objects.get(name=quiz_id, quiz_owner=quiz_owner)
    except Exception:
        return HttpResponseRedirect('/quiz/dashboard')
    if request.method == 'POST':        

templates/quiz/add_question.html
{% extends 'base.html' %}
    {% load staticfiles %}
    {% block head_block %}
    <script type="text/javascript">
        let question = '';
        let numberOfAnswers = 0;
        let numberOfCorrectAnswers = 0;
        let isSelected;
        let correctAnswers = {{ correct_answers|safe }};
        let incorrectAnswers = {{ incorrect_answers|safe }};
        if ({{ is_submitted|lower }}){
            if({{ number_of_correct_answers }} > 1){
                isSelected = true;
                addNumberCorrect();
            } else {
                isSelected = false;
            }    
        }
        let isQuestion = true;

        numberInput = () => {
            input = document.getElementById('number_of_answers_input').value;
            if (input.length > 1) {
                document.getElementById('number_of_answers_input').value = input[1];
            }
        };

        addNumberCorrect = () => {
            if(!isSelected){
                let newInput = document.createElement('input');
                let newLabel = document.createElement('label');
                newLabel.setAttribute('for', 'number_correct');
                newLabel.setAttribute('id', 'number_correct_label');
                newLabel.innerHTML = '# of Correct Answers:';
                newInput.setAttribute('type', 'number');
                newInput.setAttribute('id', 'number_correct_input');
                newInput.setAttribute('name', 'number_correct_input');
                newInput.setAttribute('oninput', 'correctNumberInput()');
                if({{ is_submitted|lower }}){
                    newInput.setAttribute('value', {{ number_of_correct_answers }});
                }
                document.getElementsByTagName('form')[0].insertBefore(newInput, document.getElementById('question_submit'));
                document.getElementsByTagName('form')[0].insertBefore(newLabel, document.getElementById('number_correct_input'));
                isSelected = true;
            }
        };

        hideNumberCorrect = () => {
            if (isSelected) {
                document.getElementById('number_correct_input').remove();
                document.getElementById('number_correct_label').remove();
            }
            isSelected = false;
        };

        correctNumberInput = () => {
            input = document.getElementById('number_correct_input').value;
            if (input.length > 1) {
                document.getElementById('number_correct_input').value = input[1];
            }
            if (input > document.getElementById('number_of_answers_input').value) {
                alert('You cannot have more correct answers than total answers.');
                document.getElementById('number_correct_input').value = '';
            }
        };

        onSubmitQuestion = () => {
            if (isQuestion) {
                question = document.getElementById('question_input').value;
                numberOfAnswers = document.getElementById('number_of_answers_input').value;
                radioElement = document.getElementsByName('multiple_correct_radio');
                if (radioElement[0].checked) {
                    numberOfCorrectAnswers = 1;
                } else {
                    numberOfCorrectAnswers = document.getElementById('number_correct_input').value;
                    document.getElementById('number_correct_input').remove();
                    document.getElementById('number_correct_label').remove();
                }
                document.getElementById('remove_elements').remove();

                let question_input = document.createElement('input');
                question_input.setAttribute('type', 'hidden');
                question_input.setAttribute('name', 'question_input');
                question_input.setAttribute('value', question);
                document.getElementsByTagName('form')[0].insertBefore(question_input, document.getElementById('question_submit'));

                let number_of_answers_input = document.createElement('input');
                number_of_answers_input.setAttribute('type', 'hidden');
                number_of_answers_input.setAttribute('name', 'number_of_answers_input');
                number_of_answers_input.setAttribute('value', numberOfAnswers);
                document.getElementsByTagName('form')[0].insertBefore(number_of_answers_input, document.getElementById('question_submit'));

                let number_of_correct_answers_input = document.createElement('input');
                number_of_correct_answers_input.setAttribute('type', 'hidden');
                number_of_correct_answers_input.setAttribute('name', 'number_of_correct_answers_input');
                number_of_correct_answers_input.setAttribute('value', numberOfCorrectAnswers);
                document.getElementsByTagName('form')[0].insertBefore(number_of_correct_answers_input, document.getElementById('question_submit'));

                for (let i = 0; i < numberOfCorrectAnswers; i++) {
                    var addLabel = document.createElement('label');
                    var addInput = document.createElement('input');

                    addLabel.setAttribute('for', 'correct_answer' + i);
                    addLabel.innerHTML = 'Correct Answer #' + (i + 1);
                    addInput.setAttribute('type', 'text');
                    addInput.setAttribute('name', 'correct_answer' + i);
                    addInput.setAttribute('id', 'correct_answer' + i);
                    if({{ is_submitted|lower }}){
                        addInput.setAttribute('value', correctAnswers[i]);
                    }

                    document.getElementsByTagName('form')[0].insertBefore(addLabel, document.getElementById('question_submit'));
                    document.getElementsByTagName('form')[0].insertBefore(addInput, document.getElementById('question_submit'));
                }

                for (let i = 0; i < numberOfAnswers - numberOfCorrectAnswers; i++) {
                    var addLabel = document.createElement('label');
                    var addInput = document.createElement('input');

                    addLabel.setAttribute('for', 'incorrect_answer' + i);
                    addLabel.innerHTML = 'Incorrect Answer #' + (i + 1);
                    addInput.setAttribute('type', 'text');
                    addInput.setAttribute('name', 'incorrect_answer' + i);
                    addInput.setAttribute('id', 'incorrect_answer' + i);
                    if({{ is_submitted|lower }}){
                        addInput.setAttribute('value', incorrectAnswers[i]);
                    }

                    document.getElementsByTagName('form')[0].insertBefore(addLabel, document.getElementById('question_submit'));
                    document.getElementsByTagName('form')[0].insertBefore(addInput, document.getElementById('question_submit'));
                }
                isQuestion = false;
            } else {
                document.getElementById('question_submit').setAttribute('type', 'submit');
                document.getElementsByTagName('form')[0].setAttribute('method', 'post');
            }
        };
    </script>
    {% endblock %}
    {% block body_block %}
        <h1>Add Question</h1>
        <button class="submit_button"><a href="{% url 'quiz:edit_quiz' quiz_id=quiz.name %}">Go Back</a></button>
        {% if isError %}
            <div class="error">
                <h4>{{ error }}</h4>
            </div>
        {% endif %}
        <div class="add_question_form_container">
            <form method="dialog" action="{% url 'quiz:add_question' quiz_id=quiz.name %}">
                {% csrf_token %}
                <div id="remove_elements">
                    <label for="question_input">Question:</label>
                    <textarea name="question_input" id="question_input" rows="3">{{ question_text }}</textarea>
                    <label for="number_of_answers_input"># of Answers:</label>
                    <input type="number" name="number_of_answers_input" id="number_of_answers_input" maxlength="1" size="1"
                        oninput="numberInput()" {% if is_submitted %}value="{{ number_of_answers }}"{% endif %}>
                    <div class="add_quiz_radio_container">
                        <label for="multiple_correct_radio" class="remove_me">More than 1 correct answer?</label>
                        <input type="radio" name="multiple_correct_radio" value="0" onclick="hideNumberCorrect()" 
                            {% if number_of_correct_answers <= 1 %}checked="checked"{% endif %}>No
                        <input type="radio" name="multiple_correct_radio" value="1" onclick="addNumberCorrect()"
                            {% if number_correct_answers > 1 %}checked="checked"{% endif %}>Yes
                    </div>
                </div>                
                <button onclick="onSubmitQuestion()" class="submit_button" id="question_submit"><span>Submit</span></button>
            </form>            
        </div>
    {% endblock %}

templates/quiz/add_user_to_quiz.html
{% extends 'base.html' %}
{% block body_block %}
    <h1>Add User</h1>
    <button class="submit_button"><a href="{% url 'quiz:user_list_information' quiz_id=quiz.name %}">Go Back</a></button>
    {% if isError %}
    <div class="error">
        <h4>{{ error }}</h4>
    </div>
    {% endif %}
    {% if isSuccess %}
    <div class="success">
        <h4>{{ success }}</h4>
    </div>
    {% endif %}
    <div class="login_form_container">
        <form action="{% url 'quiz:add_user_to_quiz' quiz_id=quiz.name %}" method="post">
            {% csrf_token %}
            <label for="username_input">User:</label>
            <input type="text" id="username_input" name="username_input">
            <button class="submit_button" type="submit"><span>Submit</span></button>
        </form>
    </div>
{% endblock %}

templates/quiz/dashboard.html
{% extends 'base.html' %}
    {% block body_block %}
        <h1>Welcome to the Dashboard, {{ username }}!</h1>
        <h3 class="quiz_owner_dashboard_title">Created Quizzes</h3>
        <div class="quiz_owner_dashboard_title_container">
            <ul>
                <li class="quiz_owner_dashboard_item_name">Name</li>
                <li class="quiz_owner_dashboard_item_repeatable">Repeatable</li>
                <li class="quiz_owner_dashboard_item_edit">Edit</li>
                <li class="quiz_owner_dashboard_item_user_list">User List Information</li>
            </ul>
        </div>
        <div class="quiz_owner_dashboard">
            {% if quiz_owner_list_len < 1 %}
                <h3>You have not created any quizzes, click <a href="{% url 'quiz:new_quiz' %}">here</a> to create one.</h3>
            {% endif %}
            {% for quiz in quiz_owner_list%}
            <div class="quiz_owner_dashboard_item">
                <ul class="{% if forloop.counter0|divisibleby:2 %}even{% else %}odd{% endif %}">
                    <li class="quiz_owner_dashboard_item_name">{{ quiz.name }}</li>
                    <li class="quiz_owner_dashboard_item_repeatable">{% if quiz.is_repeatable %}Yes{% else %}No{% endif %}</li>
                    <li class="quiz_owner_dashboard_item_edit"><a href="{% url 'quiz:edit_quiz' quiz_id=quiz.name %}">Edit</a></li>
                    <li class="quiz_owner_dashboard_item_user_list"><a href="{% url 'quiz:user_list_information' quiz_id=quiz.name %}"
                        >User List Information</a></li>
                </ul>
                <hr>
            </div>
            {% endfor %}
            {% if quiz_owner_list_len > 0 %}
            <h3 class="quiz_owner_dashboard_new_quiz"><a href="{% url 'quiz:new_quiz' %}">+New Quiz</a></h3>
            {% endif %}
        </div>
        <br>
        <hr>
        <br>
        <h3 class="assigned_quiz_dashboard_title">Assigned Quizzes</h3>
        <div class="assigned_quiz_dashboard_title_container">
            <ul>
                <li class="assigned_quiz_dashboard_item_name">Quiz Name</li>
                <li class="assinged_quiz_dashboard_item_repeatable">Repeatable</li>
                <li class="assigned_quiz_dashboard_item_recent">Most Recent</li>
                <li class="assigned_quiz_dashboard_item_best">Best</li>
                <li class="assigned_quiz_dashboard_item_submission">View Submission</li>
            </ul>
        </div>
        <div class="assigned_quiz_dashboard">
            {% if quiz_member_list_len < 1 %}
            <h3>You do not have any assigned quizzes.</h3>
            {% endif %}
            {% for item in detailed_quiz_member_list%}
            <div class="assigned_quiz_dashboard_item">
                <ul class="{% if forloop.counter0|divisibleby:2 %}even{% else %}odd{% endif %}">
                    {% if item.can_take_quiz %}
                    <li class="quiz_owner_dashboard_item_name"><a href="{% url 'quiz:begin_quiz' quiz_id=item.quiz.name %}"
                        >{{ item.quiz.name }}</a></li>
                    {% else %}
                    <li class="quiz_owner_dashboard_item_name">{{ item.quiz.name }}</li>
                    {% endif %}
                    <li class="quiz_owner_dashboard_item_repeatable">{% if item.quiz.is_repeatable %}Yes{% else %}No{% endif %}</li>
                    <li class="assigned_quiz_dashboard_item_recent">{{ item.score_recent }}</li>
                    <li class="assigned_quiz_dashboard_item_best">{{ item.score_best }}</li>
                    <li class="assigned_quiz_dashboard_item_submission"><a
                            href="{% url 'quiz:view_submissions' quiz_id=item.quiz.name user_id=user_id %}">View Submissions</a></li>
                </ul>
                <hr>
            </div>
            {% endfor %}
        </div>
    {% endblock %}

templates/quiz/user_list_information.html
{% extends 'base.html' %}
{% block body_block %}
<h1>{{ quiz.name }} User List</h1>
<button class="submit_button"><a href="{% url 'quiz:dashboard' %}">Go Back</a></button>
<h3 class="quiz_owner_dashboard_title">Users</h3>
<div class="quiz_owner_dashboard_title_container">
    <ul>
        <li class="quiz_owner_dashboard_item_name">Name</li>
        <li class="quiz_owner_dashboard_item_repeatable">Score</li>
        <li class="quiz_owner_dashboard_item_edit">Remove</li>
        <li class="quiz_owner_dashboard_item_user_list">View Submission(s)</li>
    </ul>
</div>
<div class="quiz_owner_dashboard">
    {% if quiz_user_len < 1 %}
    <h3>You have not added any users, click <a href="{% url 'quiz:add_user_to_quiz' quiz_id=quiz.name %}">here</a> to add one.</h3>
    {% endif %}
    {% for user in quiz_users %}
    <div class="quiz_owner_dashboard_item">
        <ul class="{% if forloop.counter0|divisibleby:2 %}even{% else %}odd{% endif %}">
            <li class="quiz_owner_dashboard_item_name">{{ user.user.username }}</li>
            <li class="quiz_owner_dashboard_item_repeatable">#</li>
            <li class="quiz_owner_dashboard_item_edit"><a href="{% url 'quiz:edit_quiz' quiz_id=quiz.name %}">Remove</a>
            </li>
            <li class="quiz_owner_dashboard_item_user_list"><a 
                href="{% url 'quiz:view_submissions' quiz_id=quiz.name user_id=user.user.userprofile.id %}">View Submission(s)</a></li>
        </ul>
        <hr>
    </div>
    {% endfor %}
    {% if quiz_user_len > 0 %}
    <h3 class="quiz_owner_dashboard_new_quiz"><a href="{% url 'quiz:add_user_to_quiz' quiz_id=quiz.name %}">+Add User</a></h3>
    {% endif %}
</div>
{% endblock %}

templates/quiz/view_submissions.html
{% extends 'base.html'%}
{% block body_block %}
    <h1>View Submissions</h1>
    {% if score_list_len == 0 %}
        <h4>This user has not taken this quiz yet.</h4>
    {% endif %}
    {% if is_user_list_information %}
    <button class="submit_button"><a href="{% url 'quiz:user_list_information' quiz_id=quiz_id %}">Go Back</a></button>
    {% else %}
    <button class="submit_button"><a href="{% url 'quiz:dashboard' %}">Go Back</a></button>
    {% endif %}
    <form name="edit_question_form" method="POST" action="{% url 'quiz:view_submissions' quiz_id=quiz_id user_id=user_id %}">
        {% csrf_token %}
        {% for score in score_list %}
        <div class="score_list">
            <label for="score{{ forloop.counter0 }}"><strong>{{ forloop.counter }}.</strong></label>
            <input type="radio" name="score_id" value="{{ score.id }}"
                id="score{{ forloop.counter0 }}">{{ score.score }} | {{ score.created_date }}<br>
        </div>
        <hr class="score_list_hr">
        {% endfor %}
        {% if score_list_len > 0 %}
        <button class="submit_button" onclick="onSubmit()"><span>Submit</span></button>
        {% endif %}
    </form>
{% endblock %}