quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('login', views.user_login, name='user_login'),
    path('register', views.user_register, name='user_register'),
    path('logout', views.user_logout, name='user_logout'),
    path('new_quiz', views.new_quiz, name='new_quiz'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('edit/<str:quiz_id>', views.edit_quiz, name='edit_quiz'),
    path('add_question/<str:quiz_id>', views.add_question, name='add_question'),
    path('delete_question/<str:quiz_id>', views.delete_question, name='delete_question'),
    path('edit_question_main/<str:quiz_id>', views.edit_question_main, name='edit_question_main'),
    path('edit_question/<str:question_id>', views.edit_question, name='edit_question'),
    path('delete_quiz/<str:quiz_id>', views.delete_quiz, name="delete_quiz"),
    path('user_list_information/<str:quiz_id>', views.user_list_information, name="user_list_information"),
    path('add_user_to_quiz/<str:quiz_id>', views.add_user_to_quiz, name="add_user_to_quiz"),
    path('take_quiz/<str:quiz_id>', views.take_quiz, name="take_quiz"),
    path('begin_quiz/<str:quiz_id>', views.begin_quiz, name='begin_quiz'),
    path('view_submissions/<str:quiz_id>/<str:user_id>', views.view_submissions, name='view_submissions')
]

quiz_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('quiz/', include('quiz.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block head_block %}
    {% endblock %}
</head>
<body>
    <nav>
        <div class="nav-container">
            <div class="main-nav">
                <ul>
                    <li class="{% if isActive == 'home' %}active{% endif %}"><a href="{% url 'index' %}">Home</a></li
                    >{% if is_logged_in %}<li class="{% if isActive == 'dashboard' %}active{% endif %}"><a href="{% url 'quiz:dashboard' %}">Dashboard</a></li
                    ><li class="auth-nav {% if isActive == 'logout' %}active{% endif %}"><a href="{% url 'quiz:user_logout' %}">Logout</a></li
                    >{% else %}<li class="auth-nav {% if isActive == 'register' %}active{% endif %}"><a href="{% url 'quiz:user_register' %}">Register</a></li
                    ><li class="auth-nav {% if isActive == 'login' %}active{% endif %}"><a href="{% url 'quiz:user_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="body_container">
    {% block body_block %}
    {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
    {% block body_block %}
        {% if is_logged_in %}
            <h1>Welcome to the Quiz App, {{ user }}!</h1>
            <br>
            <h4>Go to the dashboard to make or take a quiz!</h4>
        {% else %}
            <h1>Welcome to the Quiz App!</h1>
            <br>
            <h4>To begin, click register in the top right hand corner. Once you have an account, you may begin creating and taking
            quizzes!</h4>            
        {% endif %}
    {% endblock %}